// src/pages/Login.jsx
import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Eye, EyeOff, Zap, ArrowRight, Code2, Brain, Trophy } from 'lucide-react';
import useAuth from '../hooks/useAuth';
import Button from '../components/ui/Button';
import Input from '../components/ui/Input';

const FEATURES = [
  { icon: Brain,  title: 'AI-Powered Questions',  desc: 'Company-specific questions generated by advanced AI' },
  { icon: Code2,  title: '4-Dimension Scoring',   desc: 'Technical, Communication, Depth & Overall scores' },
  { icon: Trophy, title: 'Track Progress',         desc: 'Full history with detailed per-question feedback' },
];

const Login = () => {
  const { login } = useAuth();
  const location  = useLocation();

  const [form,       setForm]       = useState({ email: '', password: '' });
  const [errors,     setErrors]     = useState({});
  const [showPass,   setShowPass]   = useState(false);
  const [isLoading,  setIsLoading]  = useState(false);
  const [serverError,setServerError]= useState('');

  const from = location.state?.from?.pathname || '/setup';

  const validate = () => {
    const e = {};
    if (!form.email)                        e.email    = 'Email is required';
    else if (!/\S+@\S+\.\S+/.test(form.email)) e.email = 'Enter a valid email';
    if (!form.password)                     e.password = 'Password is required';
    return e;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setServerError('');
    const errs = validate();
    if (Object.keys(errs).length) { setErrors(errs); return; }
    setErrors({});
    setIsLoading(true);
    try {
      await login(form.email, form.password);
    } catch (err) {
      setServerError(err.message);
    } finally {
      setIsLoading(false);
    }
  };

  const handleChange = (field) => (e) => {
    setForm(p => ({ ...p, [field]: e.target.value }));
    if (errors[field]) setErrors(p => ({ ...p, [field]: '' }));
  };

  return (
    <div className="min-h-screen flex">

      {/* ── LEFT PANEL ── */}
      <div className="hidden lg:flex flex-col justify-between w-[52%] bg-surface
                      border-r border-border p-12 gradient-mesh relative overflow-hidden">

        {/* Ambient orbs */}
        <div className="absolute top-20 left-10 w-72 h-72 rounded-full
                        bg-accent/5 blur-3xl pointer-events-none" />
        <div className="absolute bottom-20 right-10 w-96 h-96 rounded-full
                        bg-success/5 blur-3xl pointer-events-none" />

        {/* Logo */}
        <div className="flex items-center gap-3 relative z-10">
          <div className="w-10 h-10 rounded-xl bg-accent flex items-center justify-center
                          shadow-accent text-white font-bold text-sm">
            IF
          </div>
          <span className="text-xl font-bold text-text-primary">
            Interview<span className="text-accent">Forge</span>
          </span>
        </div>

        {/* Hero text */}
        <div className="relative z-10 space-y-6">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full
                          bg-accent/10 border border-accent/20 text-accent text-xs font-medium">
            <Zap size={12} className="fill-current" />
            AI-Powered Interview Preparation
          </div>

          <h1 className="text-5xl font-bold leading-tight">
            Ace your next
            <span className="block text-gradient">tech interview</span>
            with AI feedback
          </h1>

          <p className="text-text-muted text-lg leading-relaxed max-w-md">
            Practice with realistic questions tailored to your target company.
            Get instant, detailed feedback on every answer.
          </p>

          {/* Feature list */}
          <div className="space-y-4 pt-4">
            {FEATURES.map(({ icon: Icon, title, desc }) => (
              <div key={title} className="flex items-start gap-4">
                <div className="w-9 h-9 rounded-lg bg-accent/10 border border-accent/20
                                flex items-center justify-center flex-shrink-0">
                  <Icon size={16} className="text-accent" />
                </div>
                <div>
                  <p className="text-sm font-semibold text-text-primary">{title}</p>
                  <p className="text-xs text-text-muted mt-0.5">{desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Bottom stats */}
        <div className="relative z-10 flex items-center gap-8 pt-8 border-t border-border">
          {[['500+', 'Questions'], ['4', 'Dimensions'], ['10+', 'Companies']].map(([n, l]) => (
            <div key={l}>
              <p className="text-2xl font-bold font-mono text-accent">{n}</p>
              <p className="text-xs text-text-muted">{l}</p>
            </div>
          ))}
        </div>
      </div>

      {/* ── RIGHT PANEL ── */}
      <div className="flex-1 flex flex-col justify-center px-6 sm:px-12 lg:px-16 py-12">
        <div className="w-full max-w-md mx-auto animate-slide-up">

          {/* Mobile logo */}
          <div className="lg:hidden flex items-center gap-2 mb-8">
            <div className="w-8 h-8 rounded-lg bg-accent flex items-center justify-center
                            text-white font-bold text-xs">IF</div>
            <span className="font-bold text-text-primary">
              Interview<span className="text-accent">Forge</span>
            </span>
          </div>

          <div className="mb-8">
            <h2 className="text-3xl font-bold text-text-primary">Welcome back</h2>
            <p className="text-text-muted mt-2">Sign in to continue your preparation</p>
          </div>

          {/* Server error */}
          {serverError && (
            <div className="mb-6 p-4 rounded-xl bg-danger/10 border border-danger/20
                            text-danger text-sm flex items-center gap-2">
              <span>⚠</span> {serverError}
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-5">
            <Input
              label="Email address"
              type="email"
              placeholder="you@example.com"
              value={form.email}
              onChange={handleChange('email')}
              error={errors.email}
              autoComplete="email"
              autoFocus
            />

            <Input
              label="Password"
              type={showPass ? 'text' : 'password'}
              placeholder="Enter your password"
              value={form.password}
              onChange={handleChange('password')}
              error={errors.password}
              autoComplete="current-password"
              rightIcon={
                <button type="button" onClick={() => setShowPass(p => !p)}
                        className="hover:text-text-primary transition-colors">
                  {showPass ? <EyeOff size={16} /> : <Eye size={16} />}
                </button>
              }
            />

            <Button
              type="submit"
              className="w-full mt-2"
              isLoading={isLoading}
              loadingText="Signing in..."
              rightIcon={<ArrowRight size={16} />}
            >
              Sign in
            </Button>
          </form>

          <p className="text-center text-sm text-text-muted mt-8">
            Don't have an account?{' '}
            <Link to="/register"
                  className="text-accent hover:text-accent-hover font-medium transition-colors">
              Create one free
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Login;